# Generated by Django 4.2.1 on 2023-05-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pulisher',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pulisher',
            new_name='publisher',
        ),
    ]
