# Generated by Django 4.2.1 on 2023-05-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_pulisher_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
